const FETCH_PROMOTIONS = "FETCH_PROMOTIONS";
const FETCH_PROMOTION = "FETCH_PROMOTION";
const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";
const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const FETCH_PRODUCT = "FETCH_PRODUCT";
const FETCH_PRODUCTS_SIMILAR_PRODUCTS = "FETCH_PRODUCTS_SIMILAR_PRODUCTS";
const POST_PRODUCTS_RATING = "POST_PRODUCTS_RATING";
const FETCH_CART = "FETCH_CART";
const POST_CART_PRODUCT = "POST_CART_PRODUCT";
const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
const POST_CART_PAYMENT = "POST_CART_PAYMENT";

export {
  FETCH_PROMOTIONS,
  FETCH_PROMOTION,
  FETCH_CURRENT_USER,
  LOGIN,
  LOGOUT,
  FETCH_CATEGORIES,
  FETCH_PRODUCTS,
  FETCH_PRODUCT,
  FETCH_PRODUCTS_SIMILAR_PRODUCTS,
  POST_PRODUCTS_RATING,
  FETCH_CART,
  POST_CART_PRODUCT,
  DELETE_CART_PRODUCT,
  POST_CART_PAYMENT,
};
