const GET_PROMOTIONS_LIST = "GET_PROMOTIONS_LIST";
const GET_PROMOTIONS_LOADING = "GET_PROMOTIONS_LOADING";
const GET_PROMOTIONS_ERROR = "GET_PROMOTIONS_ERROR";

const GET_PROMOTION_DATA = "GET_PROMOTION_DATA";
const GET_PROMOTION_LOADING = "GET_PROMOTION_LOADING";
const GET_PROMOTION_ERROR = "GET_PROMOTION_ERROR";

const GET_CURRENT_USER = "GET_CURRENT_USER";
const GET_CURRENT_USER_LOADING = "GET_CURRENT_USER_LOADING";

const GET_CATEGORIES_LIST = "GET_CATEGORIES_LIST";
const GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING";
const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";

const GET_PRODUCTS_LIST = "GET_PRODUCTS_LIST";
const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

const GET_PRODUCTS_TOTAL = "GET_PRODUCTS_TOTAL";

const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";

const GET_PRODUCTS_SIMILAR_PRODUCTS_LIST = "GET_PRODUCTS_SIMILAR_PRODUCTS_LIST";
const GET_PRODUCTS_SIMILAR_PRODUCTS_LOADING = "GET_PRODUCTS_SIMILAR_PRODUCTS_LOADING";
const GET_PRODUCTS_SIMILAR_PRODUCTS_ERROR = "GET_PRODUCTS_SIMILAR_PRODUCTS_ERROR";
const GET_CART_LIST = "GET_CART_LIST";
const GET_CART_LOADING = "GET_CART_LOADING";
const GET_CART_ERROR = "GET_CART_ERROR";
const GET_CART_TOTAL_PRICE = "GET_CART_TOTAL_PRICE";

export {
  GET_PROMOTIONS_LIST,
  GET_PROMOTIONS_LOADING,
  GET_PROMOTIONS_ERROR,
  GET_PROMOTION_DATA,
  GET_PROMOTION_LOADING,
  GET_PROMOTION_ERROR,
  GET_CURRENT_USER,
  GET_CURRENT_USER_LOADING,
  GET_CATEGORIES_LIST,
  GET_CATEGORIES_LOADING,
  GET_CATEGORIES_ERROR,
  GET_PRODUCTS_LIST,
  GET_PRODUCTS_LOADING,
  GET_PRODUCTS_ERROR,
  GET_PRODUCTS_TOTAL,
  GET_PRODUCT_BY_ID,
  GET_PRODUCTS_SIMILAR_PRODUCTS_LIST,
  GET_PRODUCTS_SIMILAR_PRODUCTS_LOADING,
  GET_PRODUCTS_SIMILAR_PRODUCTS_ERROR,
  GET_CART_LIST,
  GET_CART_LOADING,
  GET_CART_ERROR,
  GET_CART_TOTAL_PRICE,
};
