const SET_PROMOTIONS_LIST = "SET_PROMOTIONS_LIST";
const SET_PROMOTIONS_LOADING = "SET_PROMOTIONS_LOADING";
const SET_PROMOTIONS_ERROR = "SET_PROMOTIONS_ERROR";

const SET_PROMOTION_DATA = "SET_PROMOTION_DATA";
const SET_PROMOTION_LOADING = "SET_PROMOTION_LOADING";
const SET_PROMOTION_ERROR = "SET_PROMOTION_ERROR";

const SET_CATEGORIES_LIST = "SET_CATEGORIES_LIST";
const SET_CATEGORIES_LOADING = "SET_CATEGORIES_LOADING";
const SET_CATEGORIES_ERROR = "SET_CATEGORIES_ERROR";

const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";
const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING";
const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

const SET_CURRENT_USER = "SET_CURRENT_USER";
const SET_CURRENT_USER_LOADING = "SET_CURRENT_USER_LOADING";
const SET_PRODUCTS_TOTAL = "SET_PRODUCTS_TOTAL";

const SET_PRODUCTS_SIMILAR_PRODUCTS_LIST = "SET_PRODUCTS_SIMILAR_PRODUCTS_LIST";
const SET_PRODUCTS_SIMILAR_PRODUCTS_LOADING = "SET_PRODUCTS_SIMILAR_PRODUCTS_LOADING";
const SET_PRODUCTS_SIMILAR_PRODUCTS_ERROR = "SET_PRODUCTS_SIMILAR_PRODUCTS_ERROR";
const SET_CART_LIST = "SET_CART_LIST";
const SET_CART_LOADING = "SET_CART_LOADING";
const SET_CART_ERROR = "SET_CART_ERROR";

export {
  SET_PROMOTIONS_LIST,
  SET_PROMOTIONS_LOADING,
  SET_PROMOTIONS_ERROR,
  SET_PROMOTION_DATA,
  SET_PROMOTION_LOADING,
  SET_PROMOTION_ERROR,
  SET_CURRENT_USER_LOADING,
  SET_CURRENT_USER,
  SET_CATEGORIES_LIST,
  SET_CATEGORIES_LOADING,
  SET_CATEGORIES_ERROR,
  SET_PRODUCTS_LIST,
  SET_PRODUCTS_LOADING,
  SET_PRODUCTS_ERROR,
  SET_PRODUCTS_TOTAL,
  SET_PRODUCTS_SIMILAR_PRODUCTS_LIST,
  SET_PRODUCTS_SIMILAR_PRODUCTS_LOADING,
  SET_PRODUCTS_SIMILAR_PRODUCTS_ERROR,
  SET_CART_LIST,
  SET_CART_LOADING,
  SET_CART_ERROR,
};
