export { default as CartView } from "./CartView.vue";
export { default as HomeView } from "./HomeView.vue";
export { default as LoginView } from "./LoginView.vue";
export { default as NotFoundView } from "./NotFoundView.vue";
export { default as ProductView } from "./ProductView.vue";
export { default as PromotionView } from "./PromotionView.vue";
export { default as RegisterView } from "./RegisterView.vue";
export { default as SearchView } from "./SearchView.vue";
export { default as AboutView } from "./AboutView.vue";
